server:
    port: 45446

spring:
  application:
    name: shadow-device
  profiles:
  - dev
  postgresql:
    datasource:
      #jdbc-url : jdbc:postgresql://172.31.28.38:5433/ami
      #jdbc-url : jdbc:postgresql://172.31.17.52:5432/ami
      jdbc-url : jdbc:postgresql://10.101.101.208:5432/ami
      driver-class-name: org.postgresql.Driver
      username: amiuser
      password: ami1234
      type: com.zaxxer.hikari.HikariDataSource
      pool-name : ami-batch-dbcp-postgresql
  mysql:
    datasource:
      jdbc-url: jdbc:mariadb://210.97.40.115:3306/piggybank2?allowMultiQueries=true
      #jdbc-url: jdbc:mariadb://piggybank2-db.caiafcuktsql.ap-northeast-2.rds.amazonaws.com:3306/piggybank2?allowMultiQueries=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: piggy2svr
      password: Run&gun26811
      type: com.zaxxer.hikari.HikariDataSource
      pool-name: ami-batch-dbcp-mysql

mybatis:
  mapper-locations:
  - classpath*:mapper/*.xml
  - classpath*:mapper/**/*.xml
  type-aliases-package: 
    kr.net.herit.rookie.*.*.dto.entity.**
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: file:../config/logback-spring-dev.xml
  
# 참고 사이트
# http://www.cronmaker.com/;jsessionid=node017wytoozjhr9li45k2xw9epjj329715.node0?0
quartz:
  realtime-statistics-property:
    enable: false
    schedule: "0 0/5 * * * ?"        # 5분마다 실행
  hour-statistics-property:
    enable: false
    schedule: "0 0/15 * * * ?"        # 15분마다 실행
  day-statistics-property:
    enable: false
    schedule: "0 30 * * * ?"        # 매시 30분에 실행
  month-statistics-property:
    enable: false
    schedule: "0 30 3 * * ?"        # 매일 3시30분에 실행
  shadow-device-property:
    enable: true
    schedule: "0 0/5 * * * ?"

device-config:
  jsonpath: ./config/device-config.json
  url: http://piggybank2.heviton.com:18080

select-stat:
  realtime-interval-minute: 10

management:        # prometheus, grafana 연동을 위한 설정
  endpoint:
    gateway:
      enable: true
  endpoints:
    web:
      base-path: "/tools/shadow-device/actuator"
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}